name: Swift

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild
    - name: GitHub Action for Danger-Swift + SwiftLint
      uses: 417-72KI/danger-swiftlint@v3.0.0

