name: Swift

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Swift
      uses: fwal/setup-swift@v1.7.0
      with:
      # Swift version to configure
        swift-version: 5.4 # default is 5.4
    - uses: actions/checkout@v2
    - name: GitHub Action for Danger-Swift + SwiftLint
      uses: 417-72KI/danger-swiftlint@v3.0.0
    - name: Build
      run: xcodebuild

